### ISSUE TITLE
 NameError: global name 'memoryview' is not defined

### ISSUE THREAD

**Issue by zlkbdotnet** [hustcc/webhookit#4]
当我使用 webhookit -c config.py ，开始监听时，直接在网页请求访问时，就直接报错
提示:
[E 170818 10:08:46 iostream:554] Uncaught exception, closing connection.
    Traceback (most recent call last):
      File "/usr/lib64/python2.6/site-packages/tornado/iostream.py", line 519, in _handle_events
        self._handle_read()
      File "/usr/lib64/python2.6/site-packages/tornado/iostream.py", line 663, in _handle_read
        self._read_from_buffer(pos)
      File "/usr/lib64/python2.6/site-packages/tornado/iostream.py", line 778, in _read_from_buffer
        self._run_read_callback(pos, False)
      File "/usr/lib64/python2.6/site-packages/tornado/iostream.py", line 687, in _run_read_callback
        future.set_result(self._consume(size))
      File "/usr/lib64/python2.6/site-packages/tornado/iostream.py", line 910, in _consume
        b = (memoryview(self._read_buffer)
    NameError: global name 'memoryview' is not defined
[E 170818 10:08:46 ioloop:638] Exception in callback None
    Traceback (most recent call last):
      File "/usr/lib64/python2.6/site-packages/tornado/ioloop.py", line 888, in start
        handler_func(fd_obj, events)
      File "/usr/lib64/python2.6/site-packages/tornado/stack_context.py", line 277, in null_wrapper
        return fn(*args, **kwargs)
      File "/usr/lib64/python2.6/site-packages/tornado/iostream.py", line 519, in _handle_events
        self._handle_read()
      File "/usr/lib64/python2.6/site-packages/tornado/iostream.py", line 663, in _handle_read
        self._read_from_buffer(pos)
      File "/usr/lib64/python2.6/site-packages/tornado/iostream.py", line 778, in _read_from_buffer
        self._run_read_callback(pos, False)
      File "/usr/lib64/python2.6/site-packages/tornado/iostream.py", line 687, in _run_read_callback
        future.set_result(self._consume(size))
      File "/usr/lib64/python2.6/site-packages/tornado/iostream.py", line 910, in _consume
        b = (memoryview(self._read_buffer)
    NameError: global name 'memoryview' is not defined
[E 170818 10:08:46 iostream:554] Uncaught exception, closing connection.
    Traceback (most recent call last):
      File "/usr/lib64/python2.6/site-packages/tornado/iostream.py", line 519, in _handle_events
        self._handle_read()
      File "/usr/lib64/python2.6/site-packages/tornado/iostream.py", line 663, in _handle_read
        self._read_from_buffer(pos)
      File "/usr/lib64/python2.6/site-packages/tornado/iostream.py", line 778, in _read_from_buffer
        self._run_read_callback(pos, False)
      File "/usr/lib64/python2.6/site-packages/tornado/iostream.py", line 687, in _run_read_callback
        future.set_result(self._consume(size))
      File "/usr/lib64/python2.6/site-packages/tornado/iostream.py", line 910, in _consume
        b = (memoryview(self._read_buffer)
    NameError: global name 'memoryview' is not defined
[E 170818 10:08:46 ioloop:638] Exception in callback None
    Traceback (most recent call last):
      File "/usr/lib64/python2.6/site-packages/tornado/ioloop.py", line 888, in start
        handler_func(fd_obj, events)
      File "/usr/lib64/python2.6/site-packages/tornado/stack_context.py", line 277, in null_wrapper
        return fn(*args, **kwargs)
      File "/usr/lib64/python2.6/site-packages/tornado/iostream.py", line 519, in _handle_events
        self._handle_read()
      File "/usr/lib64/python2.6/site-packages/tornado/iostream.py", line 663, in _handle_read
        self._read_from_buffer(pos)
      File "/usr/lib64/python2.6/site-packages/tornado/iostream.py", line 778, in _read_from_buffer
        self._run_read_callback(pos, False)
      File "/usr/lib64/python2.6/site-packages/tornado/iostream.py", line 687, in _run_read_callback
        future.set_result(self._consume(size))
      File "/usr/lib64/python2.6/site-packages/tornado/iostream.py", line 910, in _consume
        b = (memoryview(self._read_buffer)
    NameError: global name 'memoryview' is not defined
[E 170818 10:08:47 iostream:554] Uncaught exception, closing connection.
    Traceback (most recent call last):
      File "/usr/lib64/python2.6/site-packages/tornado/iostream.py", line 519, in _handle_events
        self._handle_read()
      File "/usr/lib64/python2.6/site-packages/tornado/iostream.py", line 663, in _handle_read
        self._read_from_buffer(pos)
      File "/usr/lib64/python2.6/site-packages/tornado/iostream.py", line 778, in _read_from_buffer
        self._run_read_callback(pos, False)
      File "/usr/lib64/python2.6/site-packages/tornado/iostream.py", line 687, in _run_read_callback
        future.set_result(self._consume(size))
      File "/usr/lib64/python2.6/site-packages/tornado/iostream.py", line 910, in _consume
        b = (memoryview(self._read_buffer)
    NameError: global name 'memoryview' is not defined
[E 170818 10:08:47 ioloop:638] Exception in callback None
    Traceback (most recent call last):
      File "/usr/lib64/python2.6/site-packages/tornado/ioloop.py", line 888, in start
        handler_func(fd_obj, events)
      File "/usr/lib64/python2.6/site-packages/tornado/stack_context.py", line 277, in null_wrapper
        return fn(*args, **kwargs)
      File "/usr/lib64/python2.6/site-packages/tornado/iostream.py", line 519, in _handle_events
        self._handle_read()
      File "/usr/lib64/python2.6/site-packages/tornado/iostream.py", line 663, in _handle_read
        self._read_from_buffer(pos)
      File "/usr/lib64/python2.6/site-packages/tornado/iostream.py", line 778, in _read_from_buffer
        self._run_read_callback(pos, False)
      File "/usr/lib64/python2.6/site-packages/tornado/iostream.py", line 687, in _run_read_callback
        future.set_result(self._consume(size))
      File "/usr/lib64/python2.6/site-packages/tornado/iostream.py", line 910, in _consume
        b = (memoryview(self._read_buffer)
    NameError: global name 'memoryview' is not defined

**Comment by hustcc** [comment]
Python ，系统版本，环境需要说一下。

另外随便搜索一下就可以找到答案了：https://github.com/nkrode/RedisLive/issues/93

**Comment by zlkbdotnet** [comment]
谢谢，我也发现是tornado的问题，重新升级安装了tornado解决了，感谢您的及时回复；
不过目前遇到了新的问题，
    raise BadHostKeyException(hostname, server_key, our_server_key)
BadHostKeyException: Host key for server 192.168.1.190 does not match!
还在正在纠结中，
